spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://129.159.251.47:5432/devmark
    username: devmark
    password: "devmark"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
